targets:
  $default:
    builders:
      formkit|formkit_mapper_builder:
        enabled: true
      formkit|formkit_access_ref_builder:
        enabled: true
      formkit|formkit_auto_register_finalizer:
        enabled: true
        
builders:
  formkit_mapper_builder:
    import: "package:formkit/src/generator/build/formkit_mapper_builder.dart"
    builder_factories: ["formKitMapperBuilder"]
    build_extensions:
      .dart: [".formkit_mapper.dart"] 
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"] 


  formkit_access_ref_builder:
    import: "package:formkit/src/generator/build/formkit_access_ref_builder.dart" 
    builder_factories: ["formKitAccessRefBuilder"]
    build_extensions:
      .dart: [".formkit_access_ref"] 
    auto_apply: dependents
    build_to: source

  formkit_auto_register_finalizer:
    import: "package:formkit/src/generator/build/formkit_auto_register_finalizer_builder.dart"
    builder_factories: ["formKitAutoRegisterFinalizerBuilder"]
    build_extensions:
      r'$lib$': ["lib/formkit_auto_register.dart"]
    auto_apply: dependents
    build_to: source
    required_inputs: [".formkit_access_ref"]

post_process_builders:
  formkit_auto_register_collector:
    import: "package:formkit/src/generator/build/formkit_auto_register_builder.dart"
    builder_factory: "formKitAutoRegisterBuilder"
    input_extensions: [".formkit_access_ref"]